### ISSUE TITLE
Add HTTP endpoint for TD validation

### ISSUE THREAD

**Issue by farshidtz** [linksmart/thing-directory#11]
It would be nice to have an endpoint to validate TDs against the TD schema. 

What should the operation/endpoint look like?
* `POST /validation` is not very RESTful. 
* `GET /validation` is idempotent but some clients may not support a body in GET request.
* Add dry run query parameters to TD CRUD operation. E.g. `POST /td?dryrun`.

**Comment by dschowta** [comment]
Validation can be done in one of the following ways (motivated from [this thread](https://stackoverflow.com/questions/31967684/dry-run-strategy-for-rest-api): 
1. Provide a **separate endpoint** `POST /dry-run-td` so that a client can validate its TD
   **Pro:** the existing TD API will be clean
   **Con:** As you said it, it is not restful as we expect idempotent operation from POST method
2. Use the same endpoint, but **pass a flag** to indicate it as a dry run. 
e.g.
   -   `POST /td?dry-run=true` where the dry-run defaults to false when not given
   -   `POST /td?exec=false`  or  `POST /td?commit=false`  where the dry-run defaults to true when not given

3. Do not perform dry run at all and leave it to the client. This has the problem that the client can not sync up always with the server about the schema unless the server exposes it. 

4. Use `GET /validation` with body but some clients may not support a body in GET request.
