### ISSUE TITLE
Implement Notification API

### ISSUE THREAD

**Issue by farshidtz** [linksmart/thing-directory#45]
See https://w3c.github.io/wot-discovery/#exploration-directory-api-notification

**Comment by farshidtz** [comment]
Event storage data e.g.:
```json
[
   {
      "id": "auto increment",
      "event": "event type",
      "data" : "full td",
      "jsonpath" : "$[?(@.type=='temperature')]",
      "xpath"      : ""
   }
]
```

**Comment by dschowta** [comment]
storing jsonpath and xpath would not be helpful considering since
1. an event might match multiple jsonpath/xpath expressions
2. Server stores it unnecessarily if a client unsubscribes and never comes back
3. a client can subscribe with a new set of jsonpath/xpath filters by passing an old `Last-Event-ID`  (in case of m2m communication, this would not happen)

So I propose to store the events this way 
```json
[
   {
      "id": "auto increment",
      "event": "event type",
      "data" : "id of the TD"
   }
]
```
In case of `create` event type, the server can lookup the created TD and pass it on as part of the data
in case of `delete` event type , as per the spec, server does not have to send the full td
in case of `update` event type, the past history will be lost and only the latest td will be given. I hope this is fine as the spec also does not specify the exact behavior and usage of this information still needs to be investigated from client's perspective.  In future, in case the server needs to provide the exact change history, it can add a new field called "updatedFields" in the events history where it only stores the updates of the TD.

Filtering: Filtering can still be applied to the TDD registry and matching TDD IDs can be looked up from the history of events.

**Comment by farshidtz** [comment]
We need to maintain the data history to deliver events to disconnected clients as they originally happened.

Updated model to also consider equivalent query expressions:
```json
[
   {
      "id": "auto increment",
      "event": "event type",
      "data" : { full or partial td },
      "query" : [
          {"jsonpath": "$[?(@.title=='Terrace Temperature Sensor')]"},
          {"xpath": "*[title='Terrace Temperature Sensor'"}
      ]
   }
]
```

To calculate the patch document for update events:
https://pkg.go.dev/github.com/evanphx/json-patch#CreateMergePatch

**Comment by farshidtz** [comment]
Reference implementations:
- https://gist.github.com/ismasan/3fb75381cd2deb6bfa9c
- https://github.com/SubChord/go-sse
- https://github.com/r3labs/sse
